name: Post JSON File to Two URLs
on:
  push:
    branches:
      - main # Runs only when pushing to the main branch
  workflow_dispatch: # Allows manual trigger
  
jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Send JSON Data to First URL
        run: |
          curl -X POST "https://:Uk5VB4p0T9OacBWVpRpgGQ@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:2hBt-OOBQa-RXs_bCnNq_g/streams/AQAAAH5Vm7_x40KdgGXAMo7M0VcAAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json
            
      - name: Send JSON Data to Second URL
        run: |
          curl -X POST "https://:tL2dmzhHTXmzZTfdnqzXGA@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:2hBt-OOBQa-RXs_bCnNq_g/streams/AQAAAOKL7g8SBkWlmvg4uoeArRQAAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json
